version: '3'

services:
  master:
    build: ./
    ports:
     - "8089:8089"
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089
  
  worker:
    build: ./
    command: -f /mnt/locust/locustfile.py --worker --master-host master